2023-09-15 22:02:32,047 INFO    Thread-10 (_run_job):6060 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-09-15 22:02:32,047 INFO    Thread-10 (_run_job):6060 [wandb_setup.py:_flush():76] Configure stats pid to 6060
2023-09-15 22:02:32,048 INFO    Thread-10 (_run_job):6060 [wandb_setup.py:_flush():76] Loading settings from /home2/swethavipparla/.config/wandb/settings
2023-09-15 22:02:32,048 INFO    Thread-10 (_run_job):6060 [wandb_setup.py:_flush():76] Loading settings from /home2/swethavipparla/anlp/Assignments/A2/wandb/settings
2023-09-15 22:02:32,048 INFO    Thread-10 (_run_job):6060 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'elmo', 'entity': 'swetha20', 'root_dir': '/home2/swethavipparla/anlp/Assignments/A2', 'run_id': '7tetwvqo', 'sweep_param_path': '/home2/swethavipparla/anlp/Assignments/A2/wandb/sweep-08f8mkoc/config-7tetwvqo.yaml', 'sweep_id': '08f8mkoc'}
2023-09-15 22:02:32,048 INFO    Thread-10 (_run_job):6060 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-15 22:02:32,048 INFO    Thread-10 (_run_job):6060 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-15 22:02:32,048 INFO    Thread-10 (_run_job):6060 [wandb_init.py:_log_setup():524] Logging user logs to /home2/swethavipparla/anlp/Assignments/A2/wandb/run-20230915_220232-7tetwvqo/logs/debug.log
2023-09-15 22:02:32,048 INFO    Thread-10 (_run_job):6060 [wandb_init.py:_log_setup():525] Logging internal logs to /home2/swethavipparla/anlp/Assignments/A2/wandb/run-20230915_220232-7tetwvqo/logs/debug-internal.log
2023-09-15 22:02:32,049 INFO    Thread-10 (_run_job):6060 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f3f9c6c1360>
2023-09-15 22:02:32,049 INFO    Thread-10 (_run_job):6060 [wandb_init.py:init():564] calling init triggers
2023-09-15 22:02:32,049 INFO    Thread-10 (_run_job):6060 [wandb_init.py:init():571] wandb.init called with sweep_config: {'dropout_rate': 0.2, 'embedding_dimension': 200, 'hidden_dimension': 100, 'learning_rate': 0.01, 'optimizer': 'Adam'}
config: {}
2023-09-15 22:02:32,050 INFO    Thread-10 (_run_job):6060 [wandb_init.py:init():614] starting backend
2023-09-15 22:02:32,050 INFO    Thread-10 (_run_job):6060 [wandb_init.py:init():618] setting up manager
2023-09-15 22:02:32,060 INFO    Thread-10 (_run_job):6060 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-09-15 22:02:32,061 INFO    Thread-10 (_run_job):6060 [wandb_init.py:init():624] backend started and connected
2023-09-15 22:02:32,080 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_config_callback():1324] config_cb None None {'dropout_rate': 0.2, 'embedding_dimension': 200, 'hidden_dimension': 100, 'learning_rate': 0.01, 'optimizer': 'Adam'}
2023-09-15 22:02:32,084 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-09-15 22:02:32,084 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-09-15 22:02:32,084 INFO    Thread-10 (_run_job):6060 [wandb_init.py:init():715] updated telemetry
2023-09-15 22:02:32,085 INFO    Thread-10 (_run_job):6060 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2023-09-15 22:02:32,859 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_on_init():2220] communicating current version
2023-09-15 22:02:32,993 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_on_init():2229] got version response 
2023-09-15 22:02:32,993 INFO    Thread-10 (_run_job):6060 [wandb_init.py:init():799] starting run threads in backend
2023-09-15 22:02:36,437 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_console_start():2199] atexit reg
2023-09-15 22:02:36,438 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-09-15 22:02:36,438 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-09-15 22:02:36,438 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_redirect():2144] Redirects installed.
2023-09-15 22:02:36,439 INFO    Thread-10 (_run_job):6060 [wandb_init.py:init():840] run started, returning control to user process
2023-09-15 22:03:06,422 INFO    MainThread:6060 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-09-15 22:03:06,424 INFO    MainThread:6060 [wandb_init.py:_pause_backend():435] pausing backend
2023-09-15 22:03:29,226 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_finish():1934] finishing run swetha20/elmo/7tetwvqo
2023-09-15 22:03:29,227 ERROR   Thread-10 (_run_job):6060 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-09-15 22:03:29,227 INFO    Thread-10 (_run_job):6060 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-09-15 22:03:29,227 INFO    Thread-10 (_run_job):6060 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2023-09-15 22:03:29,228 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 1
2023-09-15 22:03:29,228 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_restore():2151] restore
2023-09-15 22:03:29,228 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_restore():2157] restore done
2023-09-15 22:03:29,230 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_restore():2151] restore
2023-09-15 22:03:29,230 INFO    Thread-10 (_run_job):6060 [wandb_run.py:_restore():2157] restore done
2023-09-15 22:03:30,271 ERROR   Thread-10 (_run_job):6060 [wandb_run.py:_atexit_cleanup():2189] Problem finishing run
Traceback (most recent call last):
  File "/tmp/ipykernel_6060/2507743021.py", line 7, in random_search
    train_loss, val_loss = train(cfg.optimizer, cfg.embedding_dimension, cfg.hidden_dimension, cfg.dropout_rate, cfg.learning_rate)
  File "/tmp/ipykernel_6060/1851690653.py", line 9, in train
    model = mdl.ELMO(embedding_matrix(word_to_ix, glove_vectors), len(word_to_ix), hidden_dimension, dropout_rate)
  File "/tmp/ipykernel_6060/1346446161.py", line 24, in embedding_matrix
    print(embedding_matrix.shape)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 640, in write
    self._old_write(data)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/iostream.py", line 664, in write
    self._schedule_flush()
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/iostream.py", line 561, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/zmq/sugar/socket.py", line 696, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 742, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 138, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 298, in _run_job
    self._function()
  File "/tmp/ipykernel_6060/2507743021.py", line 4, in random_search
    with wandb.init(config=config):
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 3121, in __exit__
    traceback.print_exception(exc_type, exc_val, exc_tb)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/traceback.py", line 121, in print_exception
    print(line, file=file, end="")
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 640, in write
    self._old_write(data)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/iostream.py", line 664, in write
    self._schedule_flush()
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/iostream.py", line 561, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/zmq/sugar/socket.py", line 696, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 742, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 138, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2177, in _atexit_cleanup
    self._on_finish()
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2412, in _on_finish
    self._footer_exit_status_info(
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 3355, in _footer_exit_status_info
    printer.display(f'{" ".join(info)}')
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/sdk/lib/printer.py", line 68, in display
    self._display(text, level=level, default_text=default_text)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/sdk/lib/printer.py", line 247, in _display
    self._display_fn_mapping(level)(text)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/wandb/sdk/lib/ipython.py", line 77, in display_html
    return display(HTML(html))
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/IPython/core/display_functions.py", line 305, in display
    publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/IPython/core/display_functions.py", line 93, in publish_display_data
    display_pub.publish(
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 102, in publish
    self._flush_streams()
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 65, in _flush_streams
    sys.stdout.flush()
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/iostream.py", line 575, in flush
    self.pub_thread.schedule(self._flush)
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/home2/swethavipparla/miniconda3/envs/anlp/lib/python3.10/site-packages/zmq/sugar/socket.py", line 696, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 742, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 138, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
